"""users table

Revision ID: 405c1cb0544b
Revises: 
Create Date: 2024-03-25 12:51:33.920674

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '405c1cb0544b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('car',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.Column('vin', sa.Integer(), nullable=True),
    sa.Column('make', sa.String(length=20), nullable=True),
    sa.Column('model', sa.String(length=20), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('BP', sa.Float(), nullable=True),
    sa.Column('SP', sa.Float(), nullable=True),
    sa.Column('bought_date', sa.DateTime(), nullable=False),
    sa.Column('sold_date', sa.DateTime(), nullable=False),
    sa.Column('available', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('vin')
    )
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_car_bought_date'), ['bought_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_car_sold_date'), ['sold_date'], unique=False)

    op.create_table('customer',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('customername', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customer_customername'), ['customername'], unique=True)

    op.create_table('payment',
    sa.Column('mpesacode', sa.String(), nullable=False),
    sa.Column('vin', sa.Integer(), nullable=False),
    sa.Column('payers_name', sa.String(), nullable=False),
    sa.Column('payers_email', sa.String(length=120), nullable=False),
    sa.Column('payers_phonenumber', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('mpesacode')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Integer(), nullable=False),
    sa.Column('product', sa.Integer(), nullable=False),
    sa.Column('efficiency', sa.Integer(), nullable=False),
    sa.Column('payment', sa.Integer(), nullable=False),
    sa.Column('overall', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=True),
    sa.Column('about_me', sa.String(length=140), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), ['username'], unique=True)

    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('body', sa.String(length=140), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('language', sa.String(length=5), nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_post_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_post_timestamp'), ['timestamp'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_post_timestamp'))
        batch_op.drop_index(batch_op.f('ix_post_customer_id'))

    op.drop_table('post')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('rating')
    op.drop_table('payment')
    with op.batch_alter_table('customer', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customer_customername'))

    op.drop_table('customer')
    with op.batch_alter_table('car', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_car_sold_date'))
        batch_op.drop_index(batch_op.f('ix_car_bought_date'))

    op.drop_table('car')
    # ### end Alembic commands ###
