"""users table

Revision ID: 78a41293bc0c
Revises: 405c1cb0544b
Create Date: 2024-03-25 13:09:10.243332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a41293bc0c'
down_revision = '405c1cb0544b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('date', sa.DateTime(), nullable=False))
        batch_op.create_index(batch_op.f('ix_payment_date'), ['date'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_date'))
        batch_op.drop_column('date')

    # ### end Alembic commands ###
